#define FRAMEWORK_VERSION "DEV1.2/1.2-feature-sysinfo"
#define FRAMEWORK_NAME "Carbon"
#define API_VERSION_MAJOR 2
#define API_VERSION_MINOR 1

#define DEPLOY_ORGANIZATION "LPQ Group"

#define MAX_KERNEL_SIZE 1024
#define MAX_UPTIME_SIZE 1024
